# Generated by Django 5.0 on 2025-07-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Review", "0002_review_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(blank=True, max_length=8192),
        ),
    ]
