# Generated by Django 5.0 on 2025-07-21 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserCustom", "0002_alter_userapp_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapp",
            name="blocked_user",
            field=models.ManyToManyField(
                related_name="Blocked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
