# Generated by Django 5.2.3 on 2025-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserCustom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapp",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
