# Generated by Django 5.2.3 on 2025-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickets",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
